spring.application.name=SecureHighloadAPI
spring.datasource.url=jdbc:postgresql://localhost:5432/secureHighloadAPI
spring.datasource.username=postgres
spring.datasource.password=123324
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.threads.virtual.enabled=true
spring.jpa.show-sql=true


securituTesting.app.secret = 3w4e5ydrtfgukbjinml756ertsdxfgchvjbknojpi978yyftdrsxfcgvytdrszeewezsw4wa32q2a3qw4sed5rcctfv
securituTesting.app.lifetime = 60000