spring.application.name=SecureHighloadAPI
spring.datasource.url=jdbc:postgresql://localhost:5432/secureHighloadAPI
spring.datasource.username=postgres
spring.datasource.password=123324
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true