spring.application.name=SecureHighloadAPI
spring.datasource.url=jdbc:postgresql://localhost:5432/secureHighloadAPI
spring.datasource.username=postgres
spring.datasource.password=123324
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.threads.virtual.enabled=true
spring.jpa.show-sql=true


api.app.secret = 3w4e5ydr980765etrwsxfgc)(@*&YGBNku76E@DVBNKJOPUYO(PIJ:NBVHFYURTYEDCvjhbkjhoyuitrutydcghvjkho2iy7tryfbnkl[p=-098vhkbj
api.app.accesslifetime = 6000
api.app.refreshlifetime = 604800000